### ISSUE TITLE
WCSim won't build without CommitHash.txt

### ISSUE THREAD

**Issue by jminock** [ANNIEsoft/WCSim#15]
I'm building a copy of WCSim for GENIE v3 integration, and WCSim will not configure because `CommitHash.txt` is missing:
`CMake Error: File /home/annie/WCSim/WCSim/CommitHash.txt does not exist.`

Is there a quick workaround?

I am building via a Docker VM following the Dockerfile steps. There are a few extra dependencies included for GENIE v3, but nothing was removed or swapped out.

**Comment by marc1uk** [comment]
Apologies, this was a bug from a simplification of the git commit recording, the file CommitHash.txt is now deprecated and removed, but wasn't removed from the CMakeLists.txt. I've updated the file to remove it, so this should now be fixed.
