### ISSUE TITLE
Genie file name not saved when using offset

### ISSUE THREAD

**Issue by jminock** [ANNIEsoft/WCSim#18]
The genie file name is not saved when the offset parameter is used for primary events. The file path is saved in all cases, but the genie file name itself is only present for ```/mygen/primariesoffset 0```

**Comment by marc1uk** [comment]
OK, did a bit of digging. The file name is retrieved when loading the genie entry in the [WCSimPrimaryGeneratorAction here](https://github.com/ANNIEsoft/WCSim/blob/annie/src/WCSimPrimaryGeneratorAction.cc#L473), then retrieved and passed into the WCSimRootEventHeader in [WCSimEventAction::EndOfEventAction here](https://github.com/ANNIEsoft/WCSim/blob/annie/src/WCSimEventAction.cc#L1299).

But it looks like the metadata tree isn't being handled correctly in the `PrimaryGeneratorAction`. The annie dirt files have a `metadata` (`tankmeta`) tree with one entry per file, and an `inputdata` (`tankflux`) tree with many entries (~one per WCSim event, assuming no dirt events with no products that intercepted the tank).
So I think [this line](https://github.com/ANNIEsoft/WCSim/blob/annie/src/WCSimPrimaryGeneratorAction.cc#L409) should be removed (or possibly moved inside the block starting at line 412 and changed to `metadata->LoadTree(nextTreeNumber);`), and [this line](https://github.com/ANNIEsoft/WCSim/blob/annie/src/WCSimPrimaryGeneratorAction.cc#L468) needs to be changed to `nufluxfilenameBranch->GetEntry(nextTreeNumber);`

**Comment by jminock** [comment]
Made a PR that includes these changes. I tested them and they work!

**Comment by marc1uk** [comment]
fixed in PR #19
